config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    scope module: :posts do
      resources :comments, only: %i[create show destroy]
      resources :likes, only: %i[create destroy]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true
end

app/models/post.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  body             :text             not null
#  post_likes_count :integer          default(0)
#  title            :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  category_id      :integer          not null
#  user_id          :integer          not null
#
# Indexes
#
#  index_posts_on_category_id  (category_id)
#  index_posts_on_user_id      (user_id)
#
# Foreign Keys
#
#  category_id  (category_id => categories.id)
#  user_id      (user_id => users.id)
#
class Post < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id', inverse_of: :posts
  belongs_to :category, inverse_of: :posts
  has_many :comments, class_name: 'PostComment', dependent: :destroy, inverse_of: :post
  has_many :likes, class_name: 'PostLike', dependent: :destroy, inverse_of: :post

  validates :title, presence: true
  validates :body, length: { maximum: 500 }
end

app/models/post_comment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: post_comments
#
#  id         :integer          not null, primary key
#  ancestry   :string
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :integer          not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_post_comments_on_ancestry  (ancestry)
#  index_post_comments_on_post_id   (post_id)
#  index_post_comments_on_user_id   (user_id)
#
# Foreign Keys
#
#  post_id  (post_id => posts.id)
#  user_id  (user_id => users.id)
#
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_ancestry

  validates :content, presence: true
end

app/models/post_like.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: post_likes
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :integer          not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_post_likes_on_post_id  (post_id)
#  index_post_likes_on_user_id  (user_id)
#
# Foreign Keys
#
#  post_id  (post_id => posts.id)
#  user_id  (user_id => users.id)
#
class PostLike < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: true
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/posts/application_controller.rb
# frozen_string_literal: true

module Posts
  class ApplicationController < ApplicationController
    def set_post
      @post = Post.find(params[:post_id])
    end
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < ApplicationController
    before_action :set_post, only: :create
    before_action :set_comment, only: :destroy

    def create
      @comment = @post.comments.build(comment_params)
      @comment.user = current_user

      if @comment.save
        flash[:success] = t('flash.comments.new.success')
        redirect_to @post
      else
        render 'posts/show', status: :unprocessable_entity
      end
    end

    def destroy
      if @comment.destroy
        flash[:success] = t('flash.comments.destroy.success')
        redirect_to post_path(@comment.post)
      else
        flash[:alert] = t('flash.comments.destroy.error')
        render 'posts/show'
      end
    end

    private

    def set_comment
      @comment = PostComment.find(params[:id])
    end

    def comment_params
      params.require(:post_comment).permit(:content, :parent_id)
    end
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

module Posts
  class LikesController < ApplicationController
    before_action :set_post, only: %i[create destroy]

    def create
      @like = @post.likes.build(user: current_user)
      redirect_to @post if @like.save
    end

    def destroy
      @like = @post.likes.find(params[:id])

      redirect_to @like.post if @like.destroy
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @comment = @post.comments.build
    @like = @post.likes.find_by(user: current_user)
  end

  def new
    @post = current_user.posts.new
  end

  def edit; end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = t('flash.posts.new.success')
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      flash[:success] = t('flash.posts.update.success')
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = t('flash.posts.delete.success')
      redirect_to root_path
    else
      flash.now[:alert] = t('flash.posts.delete.error')
      render :show
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    mapping = {
      notice: 'alert alert-info',
      success: 'alert alert-success',
      error: 'alert alert-error',
      alert: 'alert alert-warning'
    }
    mapping[level.to_sym]
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/post_comments_helper.rb
# frozen_string_literal: true

module PostCommentsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/layouts/application.html.slim
doctype html
html.h-100 lang="#{I18n.locale}"
  head
    title
      = content_for?(:title) ? yield(:title) : 'Collective Blog'
    meta[name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body.d-flex.flex-column.min-vh-100

    = render 'layouts/shared/nav'

    = render 'layouts/shared/flash'

    main.container.wrapper.flex-grow-1
      == yield

    = render 'layouts/shared/footer'

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |type, msg|
      div class="#{flash_class(type)} alert-dismissible fade show" role="alert"
        = msg
        .btn-close aria-label="Close" data-bs-dismiss="alert" type="button"

app/views/layouts/shared/_footer.html.slim
footer.d-flex.flex-wrap.justify-content-between.align-items-center.bg-dark.text-light.border-top.mt-auto
  .container
    .row.py-2
      = t('.hexlet_title', year: Time.current.year)

app/views/layouts/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.mb-3
  .container.mb-2.align-items-lg-end
    = link_to root_path, class: 'navbar-brand me-md-4' do
      = image_tag asset_pack_path('media/images/logo.png'), width: 30, alt: t('.app_logo')
    button.navbar-toggler data-bs-target='#navbarNavAltMarkup' data-bs-toggle='collapse' type='button'
      span.navbar-toggler-icon
    #navbarNavAltMarkup.collapse.navbar-collapse
      ul.navbar-nav.flex-grow-1.justify-content-end.w-100
        li.nav-item.d-flex.align-items-center.ms-auto
        - if user_signed_in?
          li.nav-item.active.me-2
          = link_to t('.add_post'), new_post_path, class: 'nav-link link-dark'
          li.nav-item.active.me-2
          = link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: 'nav-link link-dark'
        - else
          li.nav-item.active.me-2
          = link_to t('.sign_in'), new_user_session_path, class: 'nav-link link-dark'
          li.nav-item.me-2
          = link_to t('.registration'), new_user_registration_path, class: 'nav-link link-dark'

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-floating.mb-3
    = f.input :title,
            placeholder: :title,
            label: false
    = f.input :body,
            as: :text,
            placeholder: :body,
            label: false
    = f.association :category,
            collection: Category.order(:name),
            include_blank: false,
            required: false,
            value_method: :id

  .form-actions
    = f.button :submit, class: 'btn-success my-2'

app/views/posts/comments/_comment.html.slim
.card.my-4
  .card-header.small.mb-2.d-flex
    .span.fw-bold.bi-person-badge
      =< comment.user.email
    .span.mx-2.fw-light.bi-clock
      =< l(comment.created_at, format: :long)
  .card-body.d-flex
    .w-100
      .mb-3
        = comment.content
  hr.my-2
  mb-2.m-4
    a.d-block.small.text-muted(href="#new_post_comment_#{comment.id}" data-bs-toggle='collapse')
      = t('add_comment')
      - if current_user.eql?(comment.user)
        .span
          = link_to t('destroy'), post_comment_path(@post, comment),
                  method: :delete,
                  data: { confirm: t('destroy_confirmation') },
                  class: 'small text-muted'
    .collapse data-bs-target="#new_post_comment_#{comment.id}" id="new_post_comment_#{comment.id}"
      = render 'posts/comments/form', url: post_comments_path(post), comment: post.comments.build, parent_id: comment.id

    - if comment.has_children?
      - comment.children.each do |comment|
        = render partial: 'posts/comments/comment', locals: { post: post, comment: comment }

app/views/posts/comments/_form.html.slim
= simple_form_for(comment, url: url) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    - if local_assigns[:parent_id]
      = f.input :parent_id, as: :hidden, input_html: { value: parent_id }
    = f.input :content, label: false, placeholder: :content

  .form-actions
    = f.button :submit, class: 'btn-success my-2'

app/views/posts/edit.html.slim
h1 = t('.title')

= render 'form', post: @post

=> link_to t('show'), @post
'|
=< link_to t('back'), posts_path

app/views/posts/index.html.slim
- content_for :title do
  = t('.title')

.container.my-4
  h1 = t('.title')
  .row
    - @posts.each do |post|
      .col-md-12
        .card.mb-3
          .card-body
            .h5.card-title
              = link_to post.title, post, class: 'link-dark text-decoration-none'
            .card-subtitle.badge.rounded-pill.bg-info.mb-2
              = post.category.name
            .card-text
              = truncate post.body, length: 200
          .card-footer.d-flex.justify-content-between
            text-right.small.text-muted.mt-auto
              span.me-2.bi-person-badge
                =< post.creator.email
              span.me-2.bi-clock
                =< time_ago_in_words post.created_at
            text-right.small.text-danger.mt-auto
              span.me-2.bi-heart-fill
                =< post.likes.count

app/views/posts/new.html.slim
h1 = t('.title')

= render 'form', post: @post

= link_to t('back'), posts_path, class: 'btn btn-outline-primary'

app/views/posts/show.html.slim
- content_for :title do
  = t('.title')
.container.wrapper.flex-grow-1
  .row.border.mt-5.p-5.shadow.bg-light.bg-gradient.rounded-3
    .ol.breadcrumb
      .li.breadcrumb-item
        = link_to t('.title'), root_path
      .li.breadcrumb-item.active
        = @post.category.name
    .row.justify-content-center.mt-4
      article.col-12
        h1.mb-4.mb-lg-5
          = @post.title
        p = @post.body
        .d-flex.justify-content-between.mt-5.align-items-lg-end
          #button-section
            span
              - if current_user.eql?(@post.creator)
                = link_to t('edit'), edit_post_path(@post), class: 'btn btn-primary'
                = link_to t('destroy'), @post, method: :delete, data: { confirm: t('destroy_confirmation') }, class: 'btn btn-danger ms-2'
          #post-section
            span.badge.bg-info.text-white
              = @post.creator.email
            span.ms-2.badge.bg-info.text-white
              = l(@post.created_at, format: :long)
          #likes-section
            - if @like.present?
              = link_to post_like_path(@post, @like), method: :delete do
                i.bi-heart-fill.text-danger
            - else
              = link_to post_likes_path(@post), method: :post do
                i.bi-heart.text-danger
            span
              =< @post.likes.count
hr.text-dark
  .lead.mb-3
    = t('comments')
    = render 'posts/comments/form', url: post_comments_path(@post), post: @post, comment: @comment
  - @post.comments.where(ancestry: nil).each do |comment|
    = render partial: 'posts/comments/comment', locals: { post: @post, comment: comment }